// GENERATED BY _generate_primaries.py DO NOT EDIT

/*
 Copyright (C) 2026  Evan Hansen

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

package com.sbdc.loggerhead.logging.primarylogger;

import com.sbdc.loggerhead.logging.LogMode;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructArrayPublisher;
import edu.wpi.first.util.datalog.DataLog;
import edu.wpi.first.util.datalog.StructArrayLogEntry;
import edu.wpi.first.util.struct.Struct;

public final class PrimaryStructArrayLog<T, S extends Struct<T>>
    extends AbstractPrimaryLog<T[], StructArrayLogEntry<T>, StructArrayPublisher<T>> {

  public PrimaryStructArrayLog(
      String key,
      LogMode logMode,
      NetworkTableInstance ntInstance,
      DataLog dataLog,
      Struct<T> struct) {
    super(key, logMode, ntInstance, dataLog);
    switch (getMode()) {
      case FileOnly:
        setLogEntry(StructArrayLogEntry.create(dataLog, key, struct));
        break;
      case NetworkOnly:
        setPublisher(ntInstance.getStructArrayTopic(key, struct).publish());
        break;
      case Both:
        setLogEntry(StructArrayLogEntry.create(dataLog, key, struct));
        setPublisher(ntInstance.getStructArrayTopic(key, struct).publish());
        break;
    }
  }

  @Override
  protected void updateFile(T[] newValue) {
    getLogEntry().append(newValue);
  }

  @Override
  protected void updateNetwork(T[] newValue) {
    getPublisher().accept(newValue);
  }
}
