#!python3

LICENCE = """

/*
 Copyright (C) 2026  Evan Hansen

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

"""


import enum
from copy import deepcopy
import sys
from dataclasses import dataclass, field

class RunMode(enum.Enum):
  RunByRunCodeGen = 0
  RunBySelfAsLib = 1

def print_err(*x):
  print(*x, file=sys.stderr)



class JavaModifiers(enum.Enum):
  PUBLIC = "public"
  PROTECTED = "protected"
  PRIVATE = "private"
  FINAL = "final"

  @staticmethod
  def make_mod_list(modlist: list[JavaModifiers]) -> str:
    return ' '.join(map(lambda mod: mod.value, modlist))

@dataclass
class JavaDeclaration:
  name: str
  type: str
  isField: bool = False
  mods: list[JavaModifiers] = field(default_factory=list)

  def generate(self):
    return f"{JavaModifiers.make_mod_list(self.mods)} {self.type} {self.name}"

@dataclass
class JavaMethod:
  name: str
  body: str = ""
  return_: str = ""
  annotations: list[str] = field(default_factory=list)
  mods: list[JavaModifiers] = field(default_factory=list)
  is_constructor: bool = False
  params: list[JavaDeclaration] = field(default_factory=list)
  jdoc: str = ""

  def generate(self):
    mods = JavaModifiers.make_mod_list(self.mods)
    params = ','.join(map(lambda param: param.generate(), self.params))
    annotations = '\n'.join([f"@{i}" for i in self.annotations])
    jdoc = '\n'.join([" * " + i for i in self.jdoc.splitlines()])
    jdoc = '/**' + jdoc + '*/' if self.jdoc else ''
    return f"\n{jdoc}\n\n{annotations}\n{mods} {self.return_} {self.name}({params}) {{ \n{self.body} \n }}"

@dataclass
class JavaField:
  name: str
  type: str
  mods: list[JavaModifiers] = field(default_factory=list)

@dataclass
class JavaFile:
  name: str
  package: str = ""
  class_decl_extension: str = ""
  mods: list[JavaModifiers] = field(default_factory=list)
  fields: list[JavaDeclaration] = field(default_factory=list)
  methods: list[JavaMethod] = field(default_factory=list)
  imports: list[str] = field(default_factory=list)

  def generate(self):
    comment = "// GENERATED BY _generate_primaries.py DO NOT EDIT\n"
    mods = JavaModifiers.make_mod_list(self.mods)
    imports = '\n'.join(map(lambda imp: f"import {imp};", self.imports))
    header = f"package {self.package};\n{imports}\n{mods} class {self.name} {self.class_decl_extension} {{"
    fields = '\n'.join(map(lambda param: param.generate(), self.fields))

    methods = '\n'.join(map(lambda method: method.generate(), self.methods))
    methods = methods[1:]

    return '\n'.join([comment, LICENCE, header, fields, methods, '}'])





if __name__ == "__main__":
  import os

  def get_run_mode():
    return RunMode.RunByRunCodeGen

  for path, directory, files in os.walk('.\\src'):
    print_err(path, directory, files)
    for file in files:
      # print_err(path+'\\'+file, files)
      if file.endswith('.py'):
        # print_err(file)
        with open(os.path.join(path, file), 'rt') as f:
          new_globals = {} #deepcopy(globals())
          new_globals['__file__'] = os.path.join(path, file)
          exec(f.read(), new_globals, new_globals)
else:
  def get_run_mode():
    return RunMode.RunBySelfAsLib