LICENCE = """

/*
 Copyright (C) 2026  Evan Hansen

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

"""

from pathlib import Path
import sys, os

FOUND_IT = False
last = Path(__file__).resolve().parent
while not FOUND_IT:
  if 'generators' in os.listdir(last):
    FOUND_IT = True
  else:
    last = last.parent
sys.path.append(str(last))
from generators.run_code_gen import *
print(get_run_mode())

from dataclasses import dataclass, field
import enum

class JavaModifiers(enum.Enum):
  PUBLIC = "public"
  PROTECTED = "protected"
  PRIVATE = "private"
  FINAL = "final"

  @staticmethod
  def make_mod_list(modlist: list[JavaModifiers]) -> str:
    return ' '.join(map(lambda mod: mod.value, modlist))

@dataclass
class JavaDeclaration:
  name: str
  type: str
  isField: bool = False
  mods: list[JavaModifiers] = field(default_factory=list)

  def generate(self):
    return f"{JavaModifiers.make_mod_list(self.mods)} {self.type} {self.name}"

@dataclass
class JavaMethod:
  name: str
  body: str = ""
  return_: str = ""
  annotations: list[str] = field(default_factory=list)
  mods: list[JavaModifiers] = field(default_factory=list)
  is_constructor: bool = False
  params: list[JavaDeclaration] = field(default_factory=list)

  def generate(self):
    mods = JavaModifiers.make_mod_list(self.mods)
    params = ','.join(map(lambda param: param.generate(), self.params))
    annotations = '\n'.join([f"@{i}" for i in self.annotations])
    return f"{annotations}\n{mods} {self.return_} {self.name}({params}) {{ \n{self.body} \n }}"

@dataclass
class JavaField:
  name: str
  type: str
  mods: list[JavaModifiers] = field(default_factory=list)

@dataclass
class JavaFile:
  name: str
  package: str = ""
  class_decl_extension: str = ""
  mods: list[JavaModifiers] = field(default_factory=list)
  fields: list[JavaDeclaration] = field(default_factory=list)
  methods: list[JavaMethod] = field(default_factory=list)
  imports: list[str] = field(default_factory=list)

  def generate(self):
    comment = "// GENERATED BY _generate_primaries.py DO NOT EDIT\n"
    mods = JavaModifiers.make_mod_list(self.mods)
    imports = '\n'.join(map(lambda imp: f"import {imp};", self.imports))
    header = f"package {self.package};\n{imports}\n{mods} class {self.name} {self.class_decl_extension} {{"
    fields = '\n'.join(map(lambda param: param.generate(), self.fields))

    methods = '\n'.join(map(lambda method: method.generate(), self.methods))
    methods = methods[1:]

    return '\n'.join([LICENCE, comment, header, fields, methods, '}'])

    # return f"{LICENCE}\n{comment}\n{header}\n{fields}\n{methods}\n}}"


tf = JavaFile("Woah", 
              imports=["Fucker.f", "p.lefew"],
              methods=[JavaMethod("Methhod", "Testmebithc", "T", [JavaModifiers.PRIVATE], False,
                                  [JavaDeclaration("Crap", 'drudCrud', False), JavaDeclaration("Crap", 'drudCrud', False)]
                                   )],
              mods=[JavaModifiers.FINAL, JavaModifiers.PUBLIC],
              fields=[JavaDeclaration("test", "Test2", mods=[JavaModifiers.FINAL], isField=True)],
              class_decl_extension="extends AbstractPrimaryLog<String, StringLogEntry, StringPublisher>"
             )

@dataclass
class Dtype:
  name: str
  isArray: str

  def __str__(self):
    return f"{self.name}"

ALL_DTYPES = [Dtype(type_, False) for type_ in ['Boolean', 'Double', 'Integer', 'String']]
# ALL_DTYPES += [Dtype(type_.name, True, type_.name in ("Boolean, ")) for type_ in ALL_DTYPES]


IMPORT_TEMP_ALL = [
"com.sbdc.loggerhead.LogMode",
"edu.wpi.first.networktables.NetworkTableInstance",
"edu.wpi.first.util.datalog.DataLog"
]

IMPORT_TEMP_SINGLES = IMPORT_TEMP_ALL.copy() + [
  "edu.wpi.first.networktables.{dtype}{array}Publisher",
  "edu.wpi.first.util.datalog.{dtype}{array}LogEntry"
]

all_files: list[JavaFile] = []
for dtype in ALL_DTYPES:
  print("BREAK\t"*15)

  arrayIfArray = 'Array' if dtype.isArray else ''
  bracketsIfArray = '[]' if dtype.isArray else ''
  case_switch_dtype = str(dtype).lower() if dtype.isArray else str(dtype)

  class_name = f"Primary{dtype}{arrayIfArray}Log"
  imports = []
  for i in IMPORT_TEMP_SINGLES:
    try:
      imports.append(i.format(dtype=str(dtype), array=arrayIfArray))
    except Exception as e:
      imports.append(i)

  extension_text = f" extends AbstractPrimaryLog<{case_switch_dtype}{bracketsIfArray}, {dtype}{arrayIfArray}LogEntry, {dtype}{arrayIfArray}Publisher>"

  constructor_body = f"""super(key, logMode, ntInstance, dataLog);
setLogEntry(new {dtype}{arrayIfArray}LogEntry(dataLog, key));
setPublisher(ntInstance.get{dtype}{arrayIfArray}Topic(key).publish());"""

  methods = [
    JavaMethod(name=class_name, 
               is_constructor=True,
               mods=[JavaModifiers.PUBLIC],
               params=[JavaDeclaration("key", "String"),
                       JavaDeclaration("logMode", "LogMode"),
                       JavaDeclaration("ntInstance", "NetworkTableInstance"),
                       JavaDeclaration("dataLog", "DataLog")
                       ],
               body=constructor_body
               ),
    JavaMethod(name="updateFile",
               return_="void",
               is_constructor=False,
               annotations=["Override"],
               mods=[JavaModifiers.PROTECTED],
               params=[JavaDeclaration("newValue", case_switch_dtype + bracketsIfArray)],
               body="getLogEntry().append(newValue);"
               ),
    JavaMethod(name="updateNetwork",
               return_="void",
               is_constructor=False,
               annotations=["Override"],
               mods=[JavaModifiers.PROTECTED],
               params=[JavaDeclaration("newValue", case_switch_dtype + bracketsIfArray)],
               body="getPublisher().accept(newValue);"
               )
  ]

  file = JavaFile(class_name,
                  package='com.sbdc.loggerhead.primarylogger',
                  imports=imports,
                  mods=[JavaModifiers.PUBLIC, JavaModifiers.FINAL],
                  class_decl_extension=extension_text,
                  fields=[],
                  methods=methods,)
  all_files.append(file)
  print(file.generate())


for i in all_files:
  with open(Path(__file__).parent.joinpath(Path(f"{i.name}.java")), 'w') as f:
    f.write(i.generate())

# print(tf.generate())
pass

# ALL_DTYPES = ['Boolean', 'Double', 'Integer', 'String']